name: pssi_col_irlandes
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Añade flutter_speed_dial para los botones flotantes múltiples
  flutter_speed_dial: ^6.0.5
  
  # Añade url_launcher para abrir enlaces externos
  url_launcher: ^6.1.7

  # Firebase core y autenticación
  firebase_core: ^2.12.0
  firebase_auth: ^4.5.0
  
  # Cloud Firestore para manejar base de datos en Firebase
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Conjunto de buenas prácticas recomendadas por Flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Aquí puedes añadir tus assets si los necesitas en el futuro
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
